services:
  - type: web
    name: deployai-chat
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    repo: https://github.com/tatdathn-prog/deployai-chat
    branch: master
    envVars:
      - key: DEEPSEEK_KEY
        sync: false
      - key: TELEGRAM_BOT
        value: 8896024407:AAGm6tqzf_0CJaAsm-0yjU9F1Eaji7u7EK0
      - key: TELEGRAM_CHAT
        value: '8681009141'
      - key: CRM_WEBHOOK
        sync: false
      - key: HEX_URL
        value: http://192.168.178.48:5001/api/v1/generate
